version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cont-db-s
    ports:
      - "5432:5432"
